CREATE DATABASE servlet0229 CHARSET utf8mb4;
USE servlet0229;
  CREATE TABLE users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  usernsme VARCHAR(100) NOT NULL UNIQUE,
  nickname VARCHAR(100) NOT NULL,
  password VARCHAR(100)NOT NULL
);